ktor:
  application:
    modules:
      - dev.deadzone.ApplicationKt.module
  development: "$DEV_MODE:true"
  deployment:
    port: 8080
game:
  enableAdmin: "$ADMIN:false"
  host: "127.0.0.1"
  port: 7777
broadcast:
  enabled: true
  host: "0.0.0.0"
  ports: "2121,2122,2123"
  enablePolicyServer: true
policy:
  host: "0.0.0.0"
  port: 843
maria:
  url: jdbc:mariadb://0.0.0.0:3306/yourdatabasename
  user: yourusername
  password: "yourpassword"
logger:
  level: 0
  colorful: true